version: '3'
networks:
  laravel:
    driver: bridge

services:
  app:
    build: .
    container_name: '${APP_NAME}'
    restart: unless-stopped
    tty: true
    volumes:
      - ./src:/var/www
      - ./local-config/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel
    depends_on:
      - mysql
  nginx:
    image: nginx:stable
    container_name: 'nginx-${APP_NAME}'
    restart: unless-stopped
    tty: true
    ports:
      - "9000:80"
      - "448:443"
    volumes:
      - ./:/var/www
      - ./local-config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      # - ./local-config/nginx/nginx.conf.template:/etc/nginx/templates/10-variables.conf.template:ro
    networks:
      - laravel
    environment:
      app_name: '${APP_NAME}'
      app_port: '${APP_PORT}'
  mysql:
    container_name: 'mysql-${APP_NAME}'
    image: 'mysql/mysql-server:8.0'
    ports:
        - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
        MYSQL_USER: '${DB_USERNAME}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ROOT_PASSWORD: ''
        MYSQL_ROOT_HOST: '%'
        MYSQL_DATABASE: '${DB_DATABASE}'
        MYSQL_ALLOW_EMPTY_PASSWORD: 0
    volumes:
        - ./local-config/database:/var/lib/mysql
    networks:
        - laravel
    healthcheck:
        test:
            - CMD
            - mysqladmin
            - ping
            - '-p'
        retries: 3
        timeout: 5s